/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserpanelRouteImport } from './routes/userpanel'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserpanelIndexRouteImport } from './routes/userpanel/index'
import { Route as UserpanelUserproductRouteImport } from './routes/userpanel/userproduct'

const UserpanelRoute = UserpanelRouteImport.update({
  id: '/userpanel',
  path: '/userpanel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserpanelIndexRoute = UserpanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserpanelRoute,
} as any)
const UserpanelUserproductRoute = UserpanelUserproductRouteImport.update({
  id: '/userproduct',
  path: '/userproduct',
  getParentRoute: () => UserpanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/userpanel': typeof UserpanelRouteWithChildren
  '/userpanel/userproduct': typeof UserpanelUserproductRoute
  '/userpanel/': typeof UserpanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/userpanel/userproduct': typeof UserpanelUserproductRoute
  '/userpanel': typeof UserpanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/userpanel': typeof UserpanelRouteWithChildren
  '/userpanel/userproduct': typeof UserpanelUserproductRoute
  '/userpanel/': typeof UserpanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/userpanel'
    | '/userpanel/userproduct'
    | '/userpanel/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/userpanel/userproduct' | '/userpanel'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/userpanel'
    | '/userpanel/userproduct'
    | '/userpanel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  UserpanelRoute: typeof UserpanelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/userpanel': {
      id: '/userpanel'
      path: '/userpanel'
      fullPath: '/userpanel'
      preLoaderRoute: typeof UserpanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/userpanel/': {
      id: '/userpanel/'
      path: '/'
      fullPath: '/userpanel/'
      preLoaderRoute: typeof UserpanelIndexRouteImport
      parentRoute: typeof UserpanelRoute
    }
    '/userpanel/userproduct': {
      id: '/userpanel/userproduct'
      path: '/userproduct'
      fullPath: '/userpanel/userproduct'
      preLoaderRoute: typeof UserpanelUserproductRouteImport
      parentRoute: typeof UserpanelRoute
    }
  }
}

interface UserpanelRouteChildren {
  UserpanelUserproductRoute: typeof UserpanelUserproductRoute
  UserpanelIndexRoute: typeof UserpanelIndexRoute
}

const UserpanelRouteChildren: UserpanelRouteChildren = {
  UserpanelUserproductRoute: UserpanelUserproductRoute,
  UserpanelIndexRoute: UserpanelIndexRoute,
}

const UserpanelRouteWithChildren = UserpanelRoute._addFileChildren(
  UserpanelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  UserpanelRoute: UserpanelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
